"use client";

import { loadState, saveState } from "../../../(shared)/lib/storage";
import type {
  MapLayer,
  MapMarker,
  MapRegion,
  WorldEntity,
  WorldGeneratorState,
  WorldMap,
  WorldProject,
  WorldRelation
} from "../types";
import { DEFAULT_GENERATION_OPTIONS, DEFAULT_TERRAIN_WEIGHTS, generateTileMap } from "./tileWorldGenerator";

const STATE_KEY = "lifnux_world_generator_state_v2";
const LEGACY_STATE_KEY = "lifnux_world_generator_state_v1";

function nowIso() {
  return new Date().toISOString();
}

function makeId(prefix: string) {
  if (typeof crypto !== "undefined" && "randomUUID" in crypto) {
    return `${prefix}_${crypto.randomUUID()}`;
  }
  return `${prefix}_${Date.now()}_${Math.random().toString(36).slice(2)}`;
}

function createTileMap(projectId: string, mapId: string, seed: string): WorldMap {
  const now = nowIso();
  const options = { ...DEFAULT_GENERATION_OPTIONS, seed };
  return {
    id: mapId,
    projectId,
    name: "Procedural Tile World",
    description: "Seed-based tile world generated by terrain rules and adjustable weights.",
    width: options.width,
    height: options.height,
    generationOptions: options,
    terrainWeights: DEFAULT_TERRAIN_WEIGHTS,
    tiles: generateTileMap(options, DEFAULT_TERRAIN_WEIGHTS),
    tileSize: 6,
    createdAt: now,
    updatedAt: now
  };
}

function createSeedState(): WorldGeneratorState {
  const now = nowIso();
  const projectId = makeId("world_project");
  const mapId = makeId("world_map");
  const layerIds = ["continents", "rivers", "nations", "settlements", "notes"].map((name) => `${projectId}_${name}`);

  const project: WorldProject = {
    id: projectId,
    name: "Asteria Chronicle",
    description: "A sample worldbuilding project using a rule-based procedural tile map.",
    selectedMapId: mapId,
    createdAt: now,
    updatedAt: now
  };

  const map = createTileMap(projectId, mapId, DEFAULT_GENERATION_OPTIONS.seed);

  const layers: MapLayer[] = ["Continents", "Rivers", "Nations", "Settlements", "Notes"].map((name, index) => ({
    id: layerIds[index],
    projectId,
    mapId,
    name,
    visible: true,
    order: index,
    createdAt: now,
    updatedAt: now
  }));

  const entities: WorldEntity[] = [
    {
      id: makeId("entity"),
      projectId,
      name: "Lyra Voss",
      type: "Character",
      description: "A chronicler tracking treaties, borders, and hidden routes across the generated world.",
      tags: ["protagonist", "scribe"],
      relatedEntityIds: [],
      createdAt: now,
      updatedAt: now
    },
    {
      id: makeId("entity"),
      projectId,
      name: "Eldermere Accord",
      type: "Event",
      description: "A treaty that reshaped the coast cities and their trade routes.",
      tags: ["treaty", "politics"],
      relatedEntityIds: [],
      timelineDate: "Year 342, Frostwane",
      createdAt: now,
      updatedAt: now
    },
    {
      id: makeId("entity"),
      projectId,
      name: "Cindervale",
      type: "Nation",
      description: "A southern nation built around volcanic highlands and mineral trade.",
      tags: ["nation", "volcanic"],
      relatedEntityIds: [],
      createdAt: now,
      updatedAt: now
    }
  ];

  const markers: MapMarker[] = [];
  const regions: MapRegion[] = [];
  const relations: WorldRelation[] = [
    {
      id: makeId("relation"),
      projectId,
      sourceEntityId: entities[0].id,
      targetEntityId: entities[1].id,
      relationType: "involved_in",
      description: "Lyra is searching for the original record of the Eldermere Accord.",
      createdAt: now
    }
  ];

  return {
    projects: [project],
    maps: [map],
    layers,
    markers,
    regions,
    entities,
    relations,
    selectedProjectId: projectId
  };
}

function migrateState(state: WorldGeneratorState): WorldGeneratorState {
  const maps = state.maps.map((map) => {
    if (map.tiles?.length && map.generationOptions && map.terrainWeights) return map;
    const options = {
      ...DEFAULT_GENERATION_OPTIONS,
      seed: `${map.id}-seed`
    };
    return {
      ...map,
      width: options.width,
      height: options.height,
      imageDataUrl: undefined,
      drawingDataUrl: undefined,
      drawingStrokes: undefined,
      generationOptions: options,
      terrainWeights: DEFAULT_TERRAIN_WEIGHTS,
      tiles: generateTileMap(options, DEFAULT_TERRAIN_WEIGHTS),
      tileSize: 6,
      updatedAt: nowIso()
    };
  });
  return { ...state, maps };
}

export interface WorldGeneratorStore {
  load(): WorldGeneratorState;
  save(state: WorldGeneratorState): boolean;
  createProject(name: string, description?: string): WorldGeneratorState;
}

export class LocalStorageWorldGeneratorStore implements WorldGeneratorStore {
  load() {
    const current = loadState<WorldGeneratorState | null>(STATE_KEY, null);
    if (current?.projects?.length) return migrateState(current);
    const legacy = loadState<WorldGeneratorState | null>(LEGACY_STATE_KEY, null);
    if (legacy?.projects?.length) {
      const migrated = migrateState(legacy);
      this.save(migrated);
      return migrated;
    }
    const seed = createSeedState();
    this.save(seed);
    return seed;
  }

  save(state: WorldGeneratorState) {
    return saveState(STATE_KEY, state);
  }

  createProject(name: string, description = "") {
    const state = this.load();
    const now = nowIso();
    const projectId = makeId("world_project");
    const mapId = makeId("world_map");
    const layerId = makeId("layer");
    const project: WorldProject = {
      id: projectId,
      name: name.trim() || "Untitled World",
      description,
      selectedMapId: mapId,
      createdAt: now,
      updatedAt: now
    };
    const map = createTileMap(projectId, mapId, `${projectId}-seed`);
    const layer: MapLayer = {
      id: layerId,
      projectId,
      mapId,
      name: "Generated Terrain",
      visible: true,
      order: 0,
      createdAt: now,
      updatedAt: now
    };
    const next = {
      ...state,
      projects: [project, ...state.projects],
      maps: [map, ...state.maps],
      layers: [layer, ...state.layers],
      selectedProjectId: projectId
    };
    this.save(next);
    return next;
  }
}

export const worldGeneratorStore: WorldGeneratorStore = new LocalStorageWorldGeneratorStore();

export const worldGeneratorStorageKeys = {
  state: STATE_KEY,
  legacyState: LEGACY_STATE_KEY
};

export const worldGeneratorId = makeId;
export const worldGeneratorNow = nowIso;
